language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8

install:
  - cabal update
  - cabal install happy --constraint 'transformers <= 0.3.0.0'
  - happy --version
  - git clone -b for-ghc-mod https://github.com/DanielG/monad-journal.git
  - cabal install ./monad-journal --constraint 'transformers <= 0.3.0.0'
  - cabal install -j --only-dependencies --enable-tests

script:
  - cabal check
  - cabal sdist
  - export SRC_TGZ="$PWD/dist/$(cabal info . | awk '{print $2 ".tar.gz";exit}')"
  - rm -rf /tmp/test && mkdir -p /tmp/test
  - cd /tmp/test
  - tar -xf $SRC_TGZ && cd ghc-mod*/
  - cabal configure --enable-tests
  - cabal build
  - cabal test

matrix:
  allow_failures:
    - env: GHCVER=head
