language: c
sudo: false

cache:
  apt: true
  directories:
  - $HOME/.stack
  - $HOME/.ghc-mod

addons:
  apt:
    packages:
      - libfcgi-dev
      - libgmp-dev

before_install:
  - unset CC
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --version

install:
  # - git clone --depth=1 https://github.com/DanielG/cabal-helper.git
  - stack setup --resolver=ghc-$GHCVER
  - stack install cabal-install --resolver=$RES
  - cabal update
  - stack install happy --resolver=$RES
  # - stack init --ignore-subdirs --resolver=ghc-$GHCVER ./ cabal-helper/
  # - stack init --ignore-subdirs --resolver=ghc-$GHCVER ./
  - |
    resf="ghc-$GHCVER.yaml"
    echo "resolver: ghc-$GHCVER" > "$resf"
    stack solver --update-config --stack-yaml="$resf"
    sed -i 's/^resolver:/compiler:/;s/^extra-deps:/packages:/' "$resf"
    echo "resolver: { name: 'ghc-$GHCVER', location: './$resf' }" > stack.yaml
    ir=$( stack path --snapshot-install-root )
    ls -d ${ir%/custom-ghc-*}/custom-ghc-* | grep -v "${ir%/*}" | while read i; do
      rm -rfv "$i"
    done


script:
  - cabal check
  - stack build
  - stack test ghc-mod:spec

matrix:
  matrix:
  include:
  - env: GHCVER=7.8.4 RES=lts-2.22
    compiler: ': #GHC 7.8.4'
  - env: GHCVER=7.10.3 RES=lts-6.9
    compiler: ': #GHC 7.10.3'
  - env: GHCVER=8.0.1 RES=nightly-2016-08-01
    compiler: ': #GHC 8.0.1'
