language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8

install:
  - cabal update
  - cabal install happy
  - happy --version
  - cabal install -j --only-dependencies --enable-tests

script:
  - cabal check
  - cabal sdist
  - export SRC_TGZ="$PWD/dist/$(cabal info . | awk '{print $2 ".tar.gz";exit}')"
  - rm -rf /tmp/test && mkdir -p /tmp/test
  - cd /tmp/test
  - tar -xf $SRC_TGZ && cd ghc-mod*/
  - cabal configure --enable-tests
  - cabal build
  - cabal test

matrix:
  allow_failures:
    - env: GHCVER=head
