env:
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.2

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-1.18 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.18/bin:$PATH
  - which ghc
  - ghc --version
  - which ghci
  - ghci --version
  - which cabal
  - cabal --version

install:
  - cabal update
  - mkdir sandbox
  - (cd sandbox; cabal sandbox init; cabal install happy)
  - export PATH=$PWD/.cabal-sandbox/bin:$PATH
  - happy --version
  - cabal install --only-dependencies --enable-tests

script:
  - cabal configure --enable-tests
  - cabal build
  - cabal test
  - cabal check
  - cabal sdist
  # The following scriptlet checks that the resulting source distribution can be built & installed
  - export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}');
    cd dist/;
    if [ -f "$SRC_TGZ" ]; then
      cabal install --enable-tests "$SRC_TGZ";
    else
      echo "expected '$SRC_TGZ' not found";
      exit 1;
    fi

matrix:
  allow_failures:
    - env: GHCVER=head
