packages:
- ./core
- ./cabal-helper
- .
allow-newer: true
extra-deps:
- cabal-plan-0.4.0.0
- djinn-ghc-0.0.2.3
- djinn-lib-0.0.1.3
- cabal-install-2.4.0.0
- hlint-2.1.10
- cpphs-1.20.8
- cryptohash-sha256-0.11.101.0
- hackage-security-0.5.3.0
- resolv-0.1.1.1
- ed25519-0.0.5.0
- github: bergmark/polyparse
  commit: 8a69ee7e57db798c106d8b56dce05b1dfc4fed37
resolver: nightly-2018-10-17
